[package]
name = "entia_meta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
entia_core = { path = "../entia_core" }
entia_meta_macro = { path = "../entia_meta_macro" }